"""Generate Rust-native text_unidecode replacement data.

Run from the repository root:

    uv run python scripts/generate_text_unidecode_data.py
"""

from __future__ import annotations

from pathlib import Path

from text_unidecode import _replaces

OUTPUT_PATH = Path("s2and_rust/src/text_unidecode_data.rs")
CHUNK_SIZE = 48


def _rust_escape(value: str) -> str:
    escaped: list[str] = []
    for character in value:
        codepoint = ord(character)
        if character == "\\":
            escaped.append("\\\\")
        elif character == '"':
            escaped.append('\\"')
        elif character == "\n":
            escaped.append("\\n")
        elif character == "\r":
            escaped.append("\\r")
        elif character == "\t":
            escaped.append("\\t")
        elif 0x20 <= codepoint <= 0x7E:
            escaped.append(character)
        else:
            escaped.append(f"\\x{codepoint:02x}")
    return "".join(escaped)


def main() -> None:
    """Write the Rust data module."""

    payload = "\0".join(_replaces)
    chunks = [_rust_escape(payload[index : index + CHUNK_SIZE]) for index in range(0, len(payload), CHUNK_SIZE)]
    chunk_lines = "\n".join(f'    "{chunk}",' for chunk in chunks)
    output = f"""// @generated by scripts/generate_text_unidecode_data.py.
// Source data: text-unidecode==1.3 text_unidecode/data.bin.
// Source package license metadata: Artistic License.
// Do not edit by hand.

pub(crate) const TEXT_UNIDECODE_DATA: &str = concat!(
{chunk_lines}
);
"""
    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH} ({len(_replaces)} entries, {len(payload)} bytes)")


if __name__ == "__main__":
    main()
